import { useEffect, useState } from 'react';
import { AlertTriangle, ShieldAlert, Cpu, BrainCircuit, AlignLeft, Calendar, User, MapPin } from 'lucide-react';
import api from '../api/axios';

const AIAnalysisPanel = ({ complaintId }) => {
    const [analysis, setAnalysis] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        if (!complaintId) return;
        setLoading(true);
        api.get(`/ai/${complaintId}`)
            .then(res => {
                setAnalysis(res.data);
                setLoading(false);
            })
            .catch(err => {
                console.error("AI Fetch Error:", err);
                setError("Analysis pending or unavailable.");
                setLoading(false);
            });
    }, [complaintId]);

    if (loading) return (
        <div className="bg-white p-6 rounded shadow-card animate-pulse h-64 flex flex-col items-center justify-center">
            <BrainCircuit className="w-8 h-8 text-gray-300 mb-2 animate-bounce" />
            <p className="text-gray-400 text-sm font-bold">AI is analyzing case details...</p>
        </div>
    );

    if (error || !analysis) return (
        <div className="bg-white p-6 rounded shadow-card h-full flex flex-col items-center justify-center border-l-4 border-gray-300">
            <Cpu className="w-8 h-8 text-gray-300 mb-2" />
            <p className="text-gray-400 text-sm">{error || "AI Analysis not available."}</p>
        </div>
    );

    const { severity_score, urgency_level, predicted_category, explanation, extracted_entities } = analysis;

    // Color Logic
    const getSeverityColor = (score) => {
        if (score >= 75) return 'text-red-600 bg-red-50 border-red-200';
        if (score >= 40) return 'text-orange-600 bg-orange-50 border-orange-200';
        return 'text-green-600 bg-green-50 border-green-200';
    };

    const severityColor = getSeverityColor(severity_score);

    return (
        <div className="bg-white p-6 rounded shadow-card border-t-4 border-indigo-500 relative overflow-hidden">
            {/* Background Decoration */}
            <BrainCircuit className="absolute -right-6 -top-6 w-32 h-32 text-indigo-50 opacity-20" />

            <div className="flex justify-between items-start mb-4 relative z-10">
                <h2 className="text-lg font-bold text-indigo-900 flex items-center gap-2">
                    <Cpu className="w-5 h-5 text-indigo-600" />
                    AI Assistive Analysis
                </h2>
                <span className="text-[10px] font-bold uppercase tracking-wider text-gray-400 border border-gray-200 px-2 py-0.5 rounded">
                    BETA
                </span>
            </div>

            {/* Disclaimer */}
            <div className="mb-6 bg-indigo-50 text-indigo-800 text-xs p-3 rounded flex gap-2 items-start opacity-75">
                <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
                <p>
                    <strong>Disclaimer:</strong> This analysis is generated by an automated system to assist officers.
                    It is <u>not</u> a replacement for human judgment. Please verify all details.
                </p>
            </div>

            <div className="space-y-6 relative z-10">

                {/* Severity & Urgency */}
                <div className="grid grid-cols-2 gap-4">
                    <div className={`p-4 rounded border flex flex-col items-center justify-center text-center ${severityColor}`}>
                        <span className="text-xs font-bold uppercase tracking-wider opacity-70 mb-1">Severity Score</span>
                        <span className="text-4xl font-extrabold">{severity_score}/100</span>
                    </div>

                    <div className="p-4 rounded border border-gray-200 bg-gray-50 flex flex-col items-center justify-center text-center">
                        <span className="text-xs font-bold uppercase tracking-wider text-gray-500 mb-1">Recommended Urgency</span>
                        <div className={`px-3 py-1 rounded font-bold text-sm inline-flex items-center gap-1
                            ${urgency_level === 'HIGH' ? 'bg-red-100 text-red-700' :
                                urgency_level === 'MEDIUM' ? 'bg-orange-100 text-orange-700' :
                                    'bg-green-100 text-green-700'}`}>
                            {urgency_level === 'HIGH' && <ShieldAlert className="w-3 h-3" />}
                            {urgency_level}
                        </div>
                    </div>
                </div>

                {/* Explanation */}
                {explanation && (
                    <div className="text-sm text-gray-600">
                        <p className="font-bold text-gray-700 mb-1 flex items-center gap-2">
                            <AlignLeft className="w-4 h-4" /> Reasoning:
                        </p>
                        <p className="italic bg-gray-50 p-2 rounded border border-gray-100">"{explanation}"</p>
                    </div>
                )}

                {/* Classification */}
                <div>
                    <span className="text-xs font-bold text-gray-500 uppercase">Predicted Category</span>
                    <p className="font-bold text-lg text-gray-800">{predicted_category}</p>
                </div>

                {/* Extracted Entities */}
                {extracted_entities && (
                    <div className="pt-4 border-t border-gray-100">
                        <h3 className="text-xs font-bold text-gray-500 uppercase mb-3">Extracted Details</h3>
                        <div className="flex flex-wrap gap-2">
                            {extracted_entities.dates?.map((d, i) => (
                                <span key={i} className="text-xs bg-blue-50 text-blue-700 px-2 py-1 rounded border border-blue-100 flex items-center gap-1">
                                    <Calendar className="w-3 h-3" /> {d}
                                </span>
                            ))}
                            {extracted_entities.times?.map((t, i) => (
                                <span key={i} className="text-xs bg-purple-50 text-purple-700 px-2 py-1 rounded border border-purple-100 flex items-center gap-1">
                                    <Calendar className="w-3 h-3" /> {t}
                                </span>
                            ))}
                            {extracted_entities.phone_numbers?.map((p, i) => (
                                <span key={i} className="text-xs bg-green-50 text-green-700 px-2 py-1 rounded border border-green-100 flex items-center gap-1">
                                    <User className="w-3 h-3" /> {p}
                                </span>
                            ))}
                            {extracted_entities.emails?.map((e, i) => (
                                <span key={i} className="text-xs bg-yellow-50 text-yellow-700 px-2 py-1 rounded border border-yellow-100 flex items-center gap-1">
                                    <User className="w-3 h-3" /> {e}
                                </span>
                            ))}
                            {(!extracted_entities.dates?.length && !extracted_entities.phone_numbers?.length) && (
                                <span className="text-xs text-gray-400">No specific entities detected.</span>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AIAnalysisPanel;
